### ISSUE TITLE
 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ryanf86** [blha303/plus7-tools#1]
Im getting the 'NoneType' error for quite a few shows.

Are you able to help?

I've added the shows its happening to below the terminal output

plus7-tools ryan$ ./get-all-eps.sh i-dream-of-jeannie
Added 9 URLs
Traceback (most recent call last):
  File "./get-plus7-urls.py", line 28, in <module>
    print "\n".join(main())
  File "./get-plus7-urls.py", line 19, in main
    soup = bs4.BeautifulSoup(urllib2.urlopen("https://au.tv.yahoo.com" + soup.find('a', {'class': 'paginate'})["data-url"]).read(), "html.parser")
TypeError: 'NoneType' object has no attribute '__getitem__'

Here are some of the other shows that are failing
800-words
aquarius
australias-best-houses
bates-motel
bewitched
grimm
hannibal

Working Shows:
all-saints
the-blacklist
other-space

**Comment by blha303** [comment]
Ah, I made the assumption that there would always be more than one page of results. Bit odd that 800 Words didn't work, that's the show I used for testing. Pushed a commit that fixes it (9d256db)

re the 800 words comment above, now I see that they made a whole lot of extras that pushed the episodes off the first page, and I stop looking after I read a page without any episodes.
